### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-cli/meta#146]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You most likely won't be able to transfer your repository directly, if so you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by epage** [comment]
I think moving to https://github.com/rust-cli might be more appropriate.

I'd go ahead and do this except it looks like I lost my privileges through some shuffling of things.  Maybe @Dylan-DPC  can do it.

**Comment by deg4uss3r** [comment]
I feel like we should keep the book under `rust-lang` (with lots of links to `rust-cli` and its repositories) since we are still a working group and don't want to exclude ourselves or get forgotten. Especially, if the other working groups are moving to (or have already moved under) `rust-lang`.

**Comment by epage** [comment]
I forgot this had the book. I was mostly thinking of our issues exploring challenges in CLI domain. Seems like we should split the book from the issues and have them go to separate homes.

**Comment by XAMPPRocky** [comment]
@epage You should able to transfer the issues to a new repository. Someone with write permissions needs to volunteer to create a `rust-cli/team` or similarly named repo and transfer at the issues tagged as `tracking issue` and any others.

**Comment by XAMPPRocky** [comment]
@deg4uss3r There are working groups who do not have anything under the `rust-lang` organisation, being in the `rust-lang` group is not marker that something is official. We want to make it easier to automate some of the administration work in managing our infrastructure. One thing that does that is reducing the number of different GitHub organisations with different permissions and members.

**Comment by deg4uss3r** [comment]
@XAMPPRocky Yeah that makes sense thanks for the explanation behind the motivations. Sounds like we will discuss on the discord about the correct place to move this from the nursery.

**Comment by Dylan-DPC** [comment]
@XAMPPRocky thanks for the initiative. I'm okay with separating the book and the issue tracker. I'll move the tracker to a new repository later today.

**Comment by killercup** [comment]
I don't mind splitting the book off -- but there is one thing I do require: **We need to keep URLs to the book alive!** I have no idea if/how github can do redirects for pages when moving repos, but in the worst case we can probably keep a repo with the pages URL we currently have and just replace all the pages with HTML redirects.

cc #153 and https://github.com/rust-lang/rust/issues/66495#issuecomment-554773477 where we discuss moving the book to a place where it can be distributed with rustup.

**Comment by XAMPPRocky** [comment]
@killercup GitHub pages does not automatically redirect, you'll have to create redirect pages.
